# Reference jupyter notebook for using the "mycbr_py_api.py"

In [1]:
import pandas as pd

## How to import the MyCBRRestApi, the main class of "mycbr_py_api.py"

In [2]:
from mycbr_py_api import MyCBRRestApi as mycbr

/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:79: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (conceptID is not None) and (conceptID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:100: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (casebaseID is not None) and (casebaseID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:121: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (amalgamationFunctionID is not None) and (amalgamationFunctionID is not ''):

## Initial API calls to setup the environment properly

### 1. Initialize the class object : call for __init__(...) method

In [3]:
obj = mycbr(base_url='http://localhost:8080')

### 2. Get all the concepts from the myCBR system

In [4]:
obj.getAllConcepts()

['car']

### 3. Get all the case bases from the myCBR system

In [5]:
obj.getCaseBaseIDs()

['main_casebase']

#### 3.1. Set the default casebaseID to the first casebaseID from the return value of getCaseBaseIDs()

In [6]:
obj._setCurrentCasebaseID(obj.getCaseBaseIDs()[0])

True

In [7]:
obj._getCurrentCasebaseID()

'main_casebase'

### 4. Get all the Amalgamation Functions defined for the given concept from the myCBR system

In [8]:
obj.getAllAmalgamationFunctions()

['weighted_gsf', 'new_amal_fct', 'equal_weight_gsf']

### 5. List all the attribute names which will be used as column names for the DataFrame

##### The 'caseID' and 'similarity' tags are added appart from the attribute names of a concept

In [9]:
obj._getCurrentColumnNames()

['caseID',
 'similarity',
 'zip',
 'door',
 'code',
 'color',
 'year',
 'mile',
 'fuel',
 'ccm',
 'body',
 'speed',
 'manufacturer',
 'newAttribute',
 'price',
 'model',
 'power',
 'id']

## Sample calls for the myCBR-rest Service

### 1.1 Get all the Attributes defined for the given concept from the myCBR system

In [10]:
obj.getAllAttributes()

{'zip': 'IntegerDesc',
 'door': 'IntegerDesc',
 'code': 'IntegerDesc',
 'color': 'SymbolDesc',
 'year': 'IntegerDesc',
 'mile': 'IntegerDesc',
 'fuel': 'SymbolDesc',
 'ccm': 'IntegerDesc',
 'body': 'SymbolDesc',
 'speed': 'IntegerDesc',
 'manufacturer': 'SymbolDesc',
 'newAttribute': 'IntegerDesc',
 'price': 'FloatDesc',
 'model': 'SymbolDesc',
 'power': 'IntegerDesc',
 'id': 'IntegerDesc'}

### 1.2 Get details of an attribute using its attribute name (attributeID)

##### Where: 'owner' is the concept name, 'name' is the attributeID, 'range' is the value range of the attribute, 'isMultiple' tells if multiple values are allowed for this attribute, 'type' is the datatype of the attribute.

In [11]:
obj.getAttributeByID('body')

{'owner': 'car',
 'simFct': {'body_sym_sim': {'name': 'body_sym_sim',
   'project': 'car_mycbr_project',
   'sims': [[{'value': 1.0, 'roundedValue': 1.0},
     {'value': 0.7, 'roundedValue': 0.7},
     {'value': 0.2, 'roundedValue': 0.2},
     {'value': 0.0, 'roundedValue': 0.0},
     {'value': 0.0, 'roundedValue': 0.0},
     {'value': 0.0, 'roundedValue': 0.0}],
    [{'value': 0.7, 'roundedValue': 0.7},
     {'value': 1.0, 'roundedValue': 1.0},
     {'value': 0.5, 'roundedValue': 0.5},
     {'value': 0.0, 'roundedValue': 0.0},
     {'value': 0.0, 'roundedValue': 0.0},
     {'value': 0.0, 'roundedValue': 0.0}],
    [{'value': 0.2, 'roundedValue': 0.2},
     {'value': 0.5, 'roundedValue': 0.5},
     {'value': 1.0, 'roundedValue': 1.0},
     {'value': 0.2, 'roundedValue': 0.2},
     {'value': 0.0, 'roundedValue': 0.0},
     {'value': 0.0, 'roundedValue': 0.0}],
    [{'value': 0.0, 'roundedValue': 0.0},
     {'value': 0.0, 'roundedValue': 0.0},
     {'value': 0.2, 'roundedValue': 0.2},
     {'value': 1.0, 'roundedValue': 1.0},
     {'value': 0.5, 'roundedValue': 0.5},
     {'value': 0.7, 'roundedValue': 0.7}],
    [{'value': 0.0, 'roundedValue': 0.0},
     {'value': 0.0, 'roundedValue': 0.0},
     {'value': 0.0, 'roundedValue': 0.0},
     {'value': 0.5, 'roundedValue': 0.5},
     {'value': 1.0, 'roundedValue': 1.0},
     {'value': 0.8, 'roundedValue': 0.8}],
    [{'value': 0.0, 'roundedValue': 0.0},
     {'value': 0.0, 'roundedValue': 0.0},
     {'value': 0.0, 'roundedValue': 0.0},
     {'value': 0.7, 'roundedValue': 0.7},
     {'value': 0.8, 'roundedValue': 0.8},
     {'value': 1.0, 'roundedValue': 1.0}]],
   'isSymmetric': False,
   'attribute': 'body',
   'type': 'no.ntnu.mycbr.core.similarity.SymbolFct',
   'multipleConfig': {'type': 'MAX',
    'reuse': 'REUSE',
    'mainType': 'PARTNER_QUERY'}}},
 'name': 'body',
 'range': ['convertible',
  'roadster',
  'fastback',
  'coupe',
  'station_wagon',
  'sedan'],
 'isMultiple': False,
 'type': 'no.ntnu.mycbr.core.model.SymbolDesc'}

In [12]:
obj.getColumnNames( 'car')

['caseID',
 'similarity',
 'zip',
 'door',
 'code',
 'color',
 'year',
 'mile',
 'fuel',
 'ccm',
 'body',
 'speed',
 'manufacturer',
 'newAttribute',
 'price',
 'model',
 'power',
 'id']

In [13]:
obj._setColumnNamesForConcept( 'car')

True

In [14]:
obj._getCurrentColumnNames()

['caseID',
 'similarity',
 'zip',
 'door',
 'code',
 'color',
 'year',
 'mile',
 'fuel',
 'ccm',
 'body',
 'speed',
 'manufacturer',
 'newAttribute',
 'price',
 'model',
 'power',
 'id']

In [15]:
obj.getAllAttributeSimilarityFunctions('body')

['weighted_gsf', 'new_amal_fct', 'equal_weight_gsf']

In [16]:
obj.getCaseBaseIDs()

['main_casebase']

In [17]:
obj.addCaseBaseID('new_cb')

True

In [18]:
obj.getCaseBaseIDs()

['main_casebase', 'new_cb']

In [19]:
obj.deleteCaseBaseID('new_cb')

True

In [20]:
obj.getCaseBaseIDs()

['main_casebase']

In [21]:
obj.getAllCasesFromCaseBase().head()

,similarity,caseID,body,ccm,code,color,door,fuel,id,manufacturer,mile,model,newAttribute,power,price,speed,year,zip
0,1.0,car175,station_wagon,2000,5,black;,5,gasoline,194,bmw,32292,520i,NaN,150,43599.0,183,1996,9
1,1.0,car174,station_wagon,2000,551,green;,5,gasoline,136,bmw,41704,520i,NaN,150,39299.0,183,1995,5
2,1.0,car173,sedan,2800,341,dark_green;,4,gasoline,929,bmw,3606,328i,NaN,193,56299.0,213,1997,3
3,1.0,car172,convertible,2800,701,dark_red;,2,gasoline,894,bmw,72435,328i,NaN,193,31699.0,213,1996,0
4,1.0,car179,station_wagon,2000,607,green;,5,gasoline,344,bmw,155407,520i,NaN,150,15599.0,183,1995,8

In [22]:
obj.getCaseByCaseID( caseID='car179')

,caseID,body,ccm,code,color,door,fuel,id,manufacturer,mile,model,newAttribute,power,price,speed,year,zip
0,car179,station_wagon,2000,607,green;,5,gasoline,344,bmw,155407,520i,_unknown_,150,15599.0,183,1995,8

In [23]:
obj.getAllCases().head()

,caseID,body,ccm,code,color,door,fuel,id,manufacturer,mile,model,newAttribute,power,price,speed,year,zip
0,car175,station_wagon,2000,5,black;,5,gasoline,194,bmw,32292,520i,_unknown_,150,43599.0,183,1996,9
1,car174,station_wagon,2000,551,green;,5,gasoline,136,bmw,41704,520i,_unknown_,150,39299.0,183,1995,5
2,car173,sedan,2800,341,dark_green;,4,gasoline,929,bmw,3606,328i,_unknown_,193,56299.0,213,1997,3
3,car172,convertible,2800,701,dark_red;,2,gasoline,894,bmw,72435,328i,_unknown_,193,31699.0,213,1996,0
4,car179,station_wagon,2000,607,green;,5,gasoline,344,bmw,155407,520i,_unknown_,150,15599.0,183,1995,8

In [24]:
obj.getAllAmalgamationFunctions()

['weighted_gsf', 'new_amal_fct', 'equal_weight_gsf']

In [25]:
obj.getSimilarCasesFromEphemeralCaseBaseWithContent( caseID='car179', ephemeralCaseIDs=['car79','car842','car532','car39'], amalgamationFunctionID='rank_wtweightweighted_gsfed_gsf_all')

,similarity,caseID,body,ccm,code,color,door,fuel,id,manufacturer,mile,model,newAttribute,power,price,speed,year,zip
0,0.650,car842,station_wagon,3500,413,dark_red;,5,gasoline,767,bmw,23053,m3,NaN,320,74299.0,241,1996,0
1,0.617,car39,sedan,1800,9,dark_gray;,4,gasoline,476,bmw,43979,318i,NaN,115,30399.0,183,1995,6
2,0.564,car79,coupe,3200,155,orange;,2,gasoline,868,bmw,15741,320i,NaN,150,43899.0,241,1997,6
3,0.477,car532,station_wagon,2800,814,silver;,5,gasoline,592,mercedes-benz,121123,e_280,NaN,204,24799.0,213,1995,7

In [26]:
obj.getSimilarCasesFromEphemeralCaseBase( queryIDs=['car79','car842','car532'], ephemeralCaseIDs=['car79','car842','car532'], amalgamationFunctionID='weighted_gsf')

/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:79: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (conceptID is not None) and (conceptID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:100: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (casebaseID is not None) and (casebaseID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:121: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (amalgamationFunctionID is not None) and (amalgamationFunctionID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:79: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (conceptID is not None) and (conceptID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:100: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (casebaseID is not None) and (casebaseID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:121: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (amalgamationFunctionID is not None) and (amalgamationFunctionID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:79: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (conceptID is not None) and (conceptID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:100: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (casebaseID is not None) and (casebaseID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:121: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (amalgamationFunctionID is not None) and (amalgamationFunctionID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:79: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (conceptID is not None) and (conceptID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:100: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (casebaseID is not None) and (casebaseID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:121: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (amalgamationFunctionID is not None) and (amalgamationFunctionID is not ''):

ValueError: If using all scalar values, you must pass an index

In [36]:
obj.getSimilarCasesFromEphemeralCaseBaseWithContent( caseID='car79', ephemeralCaseIDs=['car842','car532','car39'], amalgamationFunctionID='weighted_gsf')

,similarity,caseID,body,ccm,code,color,door,fuel,id,manufacturer,mile,model,newAttribute,power,price,speed,year,zip
0,0.748,car39,sedan,1800,9,dark_gray;,4,gasoline,476,bmw,43979,318i,NaN,115,30399.0,183,1995,6
1,0.624,car842,station_wagon,3500,413,dark_red;,5,gasoline,767,bmw,23053,m3,NaN,320,74299.0,241,1996,0
2,0.543,car532,station_wagon,2800,814,silver;,5,gasoline,592,mercedes-benz,121123,e_280,NaN,204,24799.0,213,1995,7

In [37]:
obj.getEphemeralCaseBaseSelfSimilarity( ephemeralCaseIDs=['car842','car532','car39'], amalgamationFunctionID='weighted_gsf')

/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:79: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (conceptID is not None) and (conceptID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:100: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (casebaseID is not None) and (casebaseID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:121: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (amalgamationFunctionID is not None) and (amalgamationFunctionID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:79: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (conceptID is not None) and (conceptID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:100: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (casebaseID is not None) and (casebaseID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:121: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (amalgamationFunctionID is not None) and (amalgamationFunctionID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:79: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (conceptID is not None) and (conceptID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:100: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (casebaseID is not None) and (casebaseID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:121: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (amalgamationFunctionID is not None) and (amalgamationFunctionID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:79: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (conceptID is not None) and (conceptID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:100: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (casebaseID is not None) and (casebaseID is not ''):
/Users/kerstinb/dev/mycbr-rest/example/mycbr_py_api.py:121: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if (amalgamationFunctionID is not None) and (amalgamationFunctionID is not ''):

ValueError: If using all scalar values, you must pass an index

In [ ]:
ssm1 = obj.getCaseBaseSelfSimilarity( amalgamationFunctionID='weighted_gsf')

In [27]:
obj.show_ordered_ssm( ssm1, ticks_interval=5);

NameError: name 'ssm1' is not defined

In [28]:
obj.getSimilarCasesByAttribute( amalgamationFunctionID='weighted_gsf', attributeID='year', value='Yes').head()

Empty DataFrame
Columns: [similarity]
Index: []

In [29]:
obj.getAttributeByID( attributeID='year').get('range')

[1950, 2010]

In [30]:
obj.getSimilarCasesByCaseID(caseID='car144', amalgamationFunctionID='weighted_gsf')

        similarity
caseID
car144       1.000
car135       0.938
car115       0.931
car119       0.929
car67        0.914
...            ...
car579       0.413
car712       0.412
car707       0.411
car898       0.399
car887       0.399

[956 rows x 1 columns]

In [35]:
obj.getSimilarCasesByCaseID(caseID='car142', amalgamationFunctionID='weighted_gsf')

        similarity
caseID
car142       1.000
car134       0.989
car140       0.962
car141       0.960
car219       0.938
...            ...
car648       0.414
car780       0.413
car671       0.412
car712       0.411
car776       0.407

[956 rows x 1 columns]

In [32]:
obj.getSimilarCasesByMultipleCaseIDs(caseIDs=['car79', 'car842','car532','car39'], amalgamationFunctionID='weighted_gsf').head()

        car79  car842  car39  car532
car175  0.719   0.794  0.621   0.467
car174  0.718   0.793  0.621   0.467
car173  0.594   0.772  0.653   0.444
car172  0.752   0.774  0.513   0.330
car179  0.710   0.785  0.780   0.632

In [33]:
obj.getSimilarCasesByCaseIDWithContent(caseID='car79', amalgamationFunctionID='weighted_gsf').head()

,similarity,caseID,body,ccm,code,color,door,fuel,id,manufacturer,mile,model,newAttribute,power,price,speed,year,zip
0,1.0,car79,coupe,3200,155,orange;,2,gasoline,868,bmw,15741,320i,_unknown_,150,43899.0,241,1997,6
1,0.9907939920634922,car66,coupe,3200,264,red;,2,gasoline,404,bmw,133514,320i,_unknown_,150,16399.0,241,1995,6
2,0.9876419920634921,car52,coupe,3200,304,red;,2,gasoline,9,bmw,177642,320i,_unknown_,150,11399.0,241,1995,6
3,0.9421638412698412,car58,sedan,3200,330,orange;,4,gasoline,142,bmw,53225,320i,_unknown_,150,32099.0,241,1996,8
4,0.9385353253968254,car60,coupe,3200,3,dark_red;,2,gasoline,183,bmw,31802,320i,_unknown_,150,33299.0,241,1995,7